import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    id("org.gradle.application")
    id("org.jetbrains.kotlin.jvm").version("1.3.11")
    id("kotlinx-serialization").version("1.3.11")
    id("com.github.johnrengelman.shadow").version("4.0.3")
    id("com.palantir.graal").version("0.2.0")
}

repositories {
    jcenter()
    // For kotlinx-serialization-runtime until its published on jcenter or maven central
    maven("https://kotlin.bintray.com/kotlinx")
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.9.1")

    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

val mainClassName = "me.seanabraham.AppKt"

application.mainClassName = mainClassName


graal {
    mainClass(mainClassName)
    outputName("hello-speedy-world")
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}
